language: node_js

sudo: false

node_js:
  - 6.10.3

before_script:
  - travis_retry npm install

script:
  - mkdir -p build/tests/
  - npm test

notifications:
  email:
    on_success: never
    on_failure: always